### ISSUE TITLE
Show the effect of current semester to cumulative GPA

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/saspes#1]
Add the ability to show what the cumulative GPA will be once the current semester ends with the current GPA.

This is will require some way to figure out how many semesters the student has been at SAS for.

**Comment by insertcustomname** [comment]
Couldn't this use the grade history page to figure out amount of semesters and amount of credit hours(since cumulative GPA is based on credit hours per semester as well)?

**Comment by gary-kim** [comment]
That's possible. The one thing I'm worried about is the number of extra requests that must be made for that. How about a button for `calculate overall effect` that makes the requests once it is hit?

**Comment by insertcustomname** [comment]
That seems like it would work, I'll take a shot at that. Currently SAS doesn't display cumulative anywhere on powerschool right?

**Comment by insertcustomname** [comment]
One issue we need to account for is that cumulative GPA is based on credit hours as well, so I think it should calculate each semester's GPA then multiply it by the number of credit hours that semester/total amount of credit hours. I'm not too sure how that would work out with GOA courses though.

**Comment by insertcustomname** [comment]
Another issue is that during the semester the current GPA doesn't show up in the grade history but it does after the semester, I'm not entirely sure how to detect whether it's during the semester or not with the exception of using the current date.
