### ISSUE TITLE
Last semester GPA and cumulative GPA features not working

### ISSUE THREAD

**Issue by insertcustomname** [gary-kim/saspes#159]
It seems that SAS has disabled the grade history tab on powerschool, they also appear to have changed something about the page itself(which is still accessible by directly going to the https://powerschool.sas.edu.sg/guardian/termgrades.html url) causing the extension to be unable to calculate cumulative GPA and last semester GPA.

**Comment by insertcustomname** [comment]
I tried going to the https://powerschool.sas.edu.sg/guardian/termgrades.html url and it seems that the page is still visible, just no longer visible from the sidebar, still not sure why it would not cause an issue if the page is still visible.

**Comment by insertcustomname** [comment]
It seems that what we were using earlier to figure out whether the current semester has elapsed is no longer working @gary-kim, despite this semester not being over grades have already been pushed to grade history and as a result the extension is calculating the same semester twice in cumulative GPA.

**Comment by gary-kim** [comment]
That feature is still only in the dev version so we have time to figure out how to fix it. Have any ideas?

**Comment by insertcustomname** [comment]
Yeah I've been working on fixing it, I'm comparing the current term from grade history with the current term from powerschool as an additional check, if they are the same and there is two sets of grades in that terms powerschool page + it's currently during the semester, it won't add the current grades in again.
