### ISSUE TITLE
Change All Links to GitHub Page

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/saspes#17]
In the extension and some of the documentation, there are links to the project website at <https://gschool.ydgkim.com/saspowerschool/>. I'd like to deprecate this website so all links in the extension should be changed to point at the GitHub repository or removed entirely.

Let's also take some of the images from the site and move it into this repository and into the README.

Should we also look into making a dedicated page for this project and documentation that can be kept in this repository?

EDIT: Forgot to mention, README download links should probably link to the GitHub releases page. I will start adding Firefox releases there when releasing a new version.

**Comment by jadijadi** [comment]
Hi Gary. May I work on this issue?

**Comment by gary-kim** [comment]
@jadijadi Yes, please feel free to.
Thank you.

**Comment by jadijadi** [comment]
Dear Gary. Although I'm not a student from this school, liked your idea of helping others with a plugin. I've done the changes and here is your pull request: https://github.com/gary-kim/saspes/pull/18
