### ISSUE TITLE
Show 1st Semester GPA

### ISSUE THREAD

**Issue by gary-kim** [gary-kim/saspes#70]
It would be nice if the 1st semester GPA would be displayed as well during second semester.

**Comment by insertcustomname** [comment]
I'm making a pull request where I tried to address this and show first semester GPA, please note I have barely written JS before so it is fairly garbage code.

**Comment by gary-kim** [comment]
@insertcustomname Sounds great. You may want to wait a bit for #103 to be merged as that is adding classes for Assignment and Course that you may want to use and also to not deal with the rebase.
